const spaceOrMinus = "\\s*\\-*"

const movements = [
  `double${spaceOrMinus}unders*`,
  `handstand${spaceOrMinus}push${spaceOrMinus}ups*\\s+`,
  `front${spaceOrMinus}squats*`,
  `back${spaceOrMinus}squats*`,
  `overhead${spaceOrMinus}squats*`,
  `box${spaceOrMinus}jumps*`,
  `snatch`,
  `split${spaceOrMinus}jerks*`,
  `handstand${spaceOrMinus}push${spaceOrMinus}ups*`,
  `pull${spaceOrMinus}ups*`,
  `muscle${spaceOrMinus}ups*`,
  `chest${spaceOrMinus}to${spaceOrMinus}bars*`,
  `thrusters*`,
  `deadlifts*`,
  `pistols*`,
  `clusters*`,
  `lunges*`,
  `push${spaceOrMinus}press`,
  `ring${spaceOrMinus}rows+`,
  `wall${spaceOrMinus}balls*`,
  `burpees*`,
  `ring${spaceOrMinus}rows*\\s+`,
  `reverse${spaceOrMinus}flyes*`,
  `sit${spaceOrMinus}ups*`,
  `toes*${spaceOrMinus}to${spaceOrMinus}bar`,
  `clean${spaceOrMinus}&${spaceOrMinus}jerks*`,
  `clean${spaceOrMinus}and${spaceOrMinus}jerks*`,
  `power${spaceOrMinus}cleans*`,
  `hang${spaceOrMinus}cleans*`,
  `hang${spaceOrMinus}squat${spaceOrMinus}cleans*`,
  `squat${spaceOrMinus}cleans*\\s+`,
  `push${spaceOrMinus}jerks*`,
  `ground${spaceOrMinus}to${spaceOrMinus}overheads*`,
  `dip${spaceOrMinus}holds*`,
  `incline${spaceOrMinus}bench`,
  `ring${spaceOrMinus}dips*`,
  `nordics*`,
  `kettlebell${spaceOrMinus}swings*`,
  `chin${spaceOrMinus}ups*`,
  `med${spaceOrMinus}ball${spaceOrMinus}cleans*`,
  `ghds*`,
  `sumo${spaceOrMinus}deadlift${spaceOrMinus}high${spaceOrMinus}pulls*`,
  `air${spaceOrMinus}squats*`,
];

 export default movements;
